/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author KIDDO
 */
public class Chuc_NangGUI extends javax.swing.JFrame {
    private final SmartCard SmartCard;
    /**
     * Creates new form Chuc_NangGUI
     */
    public Chuc_NangGUI(SmartCard SmartCard) {
        this.SmartCard = SmartCard;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        thongTinButton = new javax.swing.JButton();
        chamCongButton = new javax.swing.JButton();
        muaDoButton = new javax.swing.JButton();
        doiPINButton = new javax.swing.JButton();
        ngatKetNoiButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        thongTinButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        thongTinButton.setText("Thông tin cá nhân");
        thongTinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thongTinButtonActionPerformed(evt);
            }
        });

        chamCongButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chamCongButton.setText("Chấm công");
        chamCongButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chamCongButtonActionPerformed(evt);
            }
        });

        muaDoButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        muaDoButton.setText("Mua đồ");
        muaDoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muaDoButtonActionPerformed(evt);
            }
        });

        doiPINButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        doiPINButton.setText("Đối mã PIN");
        doiPINButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doiPINButtonActionPerformed(evt);
            }
        });

        ngatKetNoiButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ngatKetNoiButton.setText("Thoát");
        ngatKetNoiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ngatKetNoiButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(thongTinButton)
                        .addGap(18, 18, 18)
                        .addComponent(chamCongButton)
                        .addGap(18, 18, 18)
                        .addComponent(muaDoButton)
                        .addGap(18, 18, 18)
                        .addComponent(doiPINButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(ngatKetNoiButton)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thongTinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chamCongButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(muaDoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doiPINButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ngatKetNoiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void thongTinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thongTinButtonActionPerformed
        // TODO add your handling code here:
        Nhap_PIN_GUI Nhap_PIN_GUI = new Nhap_PIN_GUI(SmartCard);
        Nhap_PIN_GUI.setVisible(true);
        // this.setVisible(false);
    }//GEN-LAST:event_thongTinButtonActionPerformed

    private void chamCongButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chamCongButtonActionPerformed
        // TODO add your handling code here:
        Cham_CongGUI Cham_CongGUI = new Cham_CongGUI(SmartCard);
        Cham_CongGUI.setVisible(true);
    }//GEN-LAST:event_chamCongButtonActionPerformed

    private void muaDoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muaDoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_muaDoButtonActionPerformed

    private void doiPINButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doiPINButtonActionPerformed
        // TODO add your handling code here:
        Doi_PIN_GUI Doi_PIN_GUI = new Doi_PIN_GUI(SmartCard);
        Doi_PIN_GUI.setVisible(true);
        // this.setVisible(false);
    }//GEN-LAST:event_doiPINButtonActionPerformed

    private void ngatKetNoiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ngatKetNoiButtonActionPerformed
        // TODO add your handling code here:
        Ket_NoiGUI Ket_NoiGUI = new Ket_NoiGUI();
        if(SmartCard.disconnectCard()) {
            Ket_NoiGUI.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_ngatKetNoiButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    // public static void main(String args[]) {
    //     /* Set the Nimbus look and feel */
    //     //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    //     /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
    //      * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
    //      */
    //     SmartCard SmartCard = new SmartCard();

    //     try {
    //         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    //             if ("Nimbus".equals(info.getName())) {
    //                 javax.swing.UIManager.setLookAndFeel(info.getClassName());
    //                 break;
    //             }
    //         }
    //     } catch (ClassNotFoundException ex) {
    //         java.util.logging.Logger.getLogger(Chuc_NangGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (InstantiationException ex) {
    //         java.util.logging.Logger.getLogger(Chuc_NangGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (IllegalAccessException ex) {
    //         java.util.logging.Logger.getLogger(Chuc_NangGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (javax.swing.UnsupportedLookAndFeelException ex) {
    //         java.util.logging.Logger.getLogger(Chuc_NangGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     }
    //     //</editor-fold>

    //     /* Create and display the form */
    //     java.awt.EventQueue.invokeLater(new Runnable() {
    //         public void run() {
    //             new Chuc_NangGUI(SmartCard).setVisible(true);
    //         }
    //     });
    // }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chamCongButton;
    private javax.swing.JButton doiPINButton;
    private javax.swing.JButton muaDoButton;
    private javax.swing.JButton ngatKetNoiButton;
    private javax.swing.JButton thongTinButton;
    // End of variables declaration//GEN-END:variables
}
