/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Model.SmartCard;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class DoiPin extends javax.swing.JPanel {
    private final SmartCard SmartCard;
    private final ChucNang_NhanVien ChucNang_NhanVien;
    /**
     * Creates new form DoiPin
     */
    public DoiPin(SmartCard SmartCard, ChucNang_NhanVien ChucNang_NhanVien) {
        this.SmartCard = SmartCard;
        this.ChucNang_NhanVien = ChucNang_NhanVien;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        newPIN = new javax.swing.JPasswordField();
        oldPIN = new javax.swing.JPasswordField();
        newPINCf = new javax.swing.JPasswordField();
        oldCB = new javax.swing.JCheckBox();
        newCB = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        luuButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Nhập lại PIN mới:");

        oldCB.setText("hiển thị");
        oldCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldCBActionPerformed(evt);
            }
        });

        newCB.setText("hiển thị");
        newCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCBActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Mã PIN:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Mã PIN mới:");

        luuButton.setBackground(new java.awt.Color(153, 255, 153));
        luuButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        luuButton.setText("Lưu");
        luuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuButtonActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("ĐỔI MÃ PIN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(jLabel4)
                .addContainerGap(265, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(luuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newPIN, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(oldPIN, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(oldCB))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(newPINCf, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(newCB)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oldPIN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oldCB))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(newPIN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPINCf, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newCB))
                .addGap(42, 42, 42)
                .addComponent(luuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void oldCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldCBActionPerformed
        // TODO add your handling code here:
        if(oldCB.isSelected()) {
            oldPIN.setEchoChar((char)0);
        } else {
            oldPIN.setEchoChar('*');
        }
    }//GEN-LAST:event_oldCBActionPerformed

    private void newCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCBActionPerformed
        // TODO add your handling code here:
        if(newCB.isSelected()) {
            newPIN.setEchoChar((char)0);
            newPINCf.setEchoChar((char)0);
        } else {
            newPIN.setEchoChar('*');
            newPINCf.setEchoChar('*');
        }
    }//GEN-LAST:event_newCBActionPerformed

    private void luuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuButtonActionPerformed
        // TODO add your handling code here:
        String op = String.valueOf(oldPIN.getPassword());
        String on = String.valueOf(newPIN.getPassword());
        String onc = String.valueOf(newPINCf.getPassword());
        byte[] oPIN = SmartCard.stringToByteArray(op);
        String stat = SmartCard.checkPIN(oPIN);
        int count = 3 - Integer.parseInt(stat);

        if(stat.equals("00")){
            if(on.equals(onc)) {
                if(on.length() == 6) {
                    if(!onc.equals(op)) {
                        byte[] nPIN = SmartCard.stringToByteArray(on);
                        if (SmartCard.changePIN(nPIN)) {
                            JOptionPane.showMessageDialog(this, "Đổi PIN thành công");
                            
                            javax.swing.JPanel parent = (javax.swing.JPanel) this.getParent();
                            parent.removeAll();
                            parent.add(new DoiPin(SmartCard, ChucNang_NhanVien));
                            parent.revalidate();
                            parent.repaint();
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Mã PIN mới không được trùng với PIN cũ");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Độ dài PIN phải gồm 6 kí tự");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Mã PIN nhập lại không khớp nhau");
            }
        } else if(!stat.equals("0")) {
            JOptionPane.showMessageDialog(this, "Đã nhập sai mã PIN " + count + "/3 lần. Sau 3 lần sai, thẻ sẽ bị khóa");
        } else {
            JOptionPane.showMessageDialog(this, "Nhập sai quá số lần cho phép, thẻ bị khóa và kết thúc phiên");
            ChucNang_NhanVien.setVisible(false);
            SmartCard.disconnectCard();
            KetNoi_GUI ketNoiGUI = new KetNoi_GUI();
            ketNoiGUI.setVisible(true); 
        }

    }//GEN-LAST:event_luuButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton luuButton;
    private javax.swing.JCheckBox newCB;
    private javax.swing.JPasswordField newPIN;
    private javax.swing.JPasswordField newPINCf;
    private javax.swing.JCheckBox oldCB;
    private javax.swing.JPasswordField oldPIN;
    // End of variables declaration//GEN-END:variables
}
